# Generated by Django 4.2.4 on 2024-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0002_remove_bdoms_almacen_remove_bdoms_alto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpPais',
            fields=[
                ('CP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Localidad', models.CharField(max_length=100)),
                ('Partido', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('REGION', models.CharField(max_length=100)),
                ('DISTRITO', models.CharField(max_length=100)),
                ('ZONA', models.CharField(max_length=100)),
                ('AMBA_INTRALOG', models.CharField(max_length=100)),
                ('ZONA_FLEX', models.CharField(max_length=100)),
                ('FLEX_INTRA', models.CharField(max_length=100)),
                ('RANGO_CP', models.CharField(max_length=100)),
                ('CPA', models.CharField(max_length=100)),
            ],
        ),
    ]
