# Generated by Django 4.2.4 on 2024-02-05 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0003_cppais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdoms',
            name='codigoPostal',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='entregasapp.cppais'),
            preserve_default=False,
        ),
    ]
