# Generated by Django 5.0.4 on 2024-05-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0006_visit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='srVisit',
        ),
    ]
