# Generated by Django 5.0.4 on 2024-05-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0007_rename_visit_srvisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='srVisit',
            new_name='srVisits',
        ),
    ]
