# Generated by Django 5.0.4 on 2024-05-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0008_rename_srvisit_srvisits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='srVisits',
            new_name='srVisit',
        ),
    ]
