# Generated by Django 5.0.4 on 2024-05-31 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0010_trackingeventca'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=50)),
                ('status_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('sign', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='srVisit',
        ),
        migrations.RemoveField(
            model_name='trackingeventca',
            name='data',
        ),
        migrations.AddField(
            model_name='trackingeventca',
            name='country_id',
            field=models.CharField(default='AR', max_length=2),
        ),
        migrations.AddField(
            model_name='trackingeventca',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingeventca',
            name='service_type',
            field=models.CharField(default='SD', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingeventca',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackingeventca',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='tracking_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='entregasapp.trackingeventca'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='tracking_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trackings', to='entregasapp.trackingeventca'),
        ),
        migrations.AlterUniqueTogether(
            name='ordertracking',
            unique_together={('pedido', 'tracking_event')},
        ),
    ]
