# Generated by Django 5.0.4 on 2024-07-12 12:37

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0011_eventdetail_ordertracking_delete_srvisit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingeventca',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='trackingeventca',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trackingeventca',
            name='service_type',
        ),
        migrations.AddField(
            model_name='trackingeventca',
            name='raw_data',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingeventca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trackingeventca',
            name='tracking_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
