# Generated by Django 5.0.4 on 2024-07-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregasapp', '0012_remove_trackingeventca_country_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
